version: '3.8'

services:
  node-app:
    container_name: node-app-prod
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        yarn start
      "
    environment:
      - NODE_ENV=production