services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-secret}@postgresdb:5432/${POSTGRES_DB:-mydb}?schema=public'
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - '3000:3000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
      - /usr/src/node-app/build
    networks:
      - node-network

  postgresdb:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge